const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
const REGISTRATION_ERROR = "REGISTRATION_ERROR";
const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
const FORGOT_PASSWORD_ERROR = "FORGOT_PASSWORD_ERROR";
const FORGOT_RESET = "FORGOT_RESET";
const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR";
const RESET_PASSWORD_RESET = "RESET_PASSWORD_RESET";
const USER_PROFILE_DATA = "USER_PROFILE_DATA";
const SET_ERROR = "SET_ERROR";
const SET_SUCCESS = "SET_SUCCESS";

export {
  REGISTRATION_SUCCESS,
  REGISTRATION_ERROR,
  FORGOT_PASSWORD_SUCCESS,
  FORGOT_PASSWORD_ERROR,
  FORGOT_RESET,
  RESET_PASSWORD_SUCCESS,
  RESET_PASSWORD_ERROR,
  RESET_PASSWORD_RESET,
  USER_PROFILE_DATA,
  SET_ERROR,
  SET_SUCCESS
}