const GET_FAVOURITES_LIST = "GET_FAVOURITES_LIST";
const FAVOURITES_TRUE = "FAVOURITES_TRUE";
const FAVOURITES_FALSE = "FAVOURITES_FALSE";
const SET_ERROR = "SET_ERROR";
const SET_SUCCESS = "SET_SUCCESS";

export {
  GET_FAVOURITES_LIST,
  FAVOURITES_TRUE,
  FAVOURITES_FALSE,
  SET_ERROR,
  SET_SUCCESS,
}