const CATEGORY_LIST = "CATEGORY_LIST";
const SUB_CATEGORY_LIST = "SUB_CATEGORY_LIST";
const CATEGORY_ERROR = "CATEGORY_ERROR";
const BUSINESS_TYPE_LIST = "BUSINESS_TYPE_LIST";
const SELLER_DATA = "SELLER_DATA";
const SET_ERROR = "SET_ERROR";
const SET_MESSAGE = "SET_MESSAGE";
const SET_SUCCESS = "SET_SUCCESS";
const BUYER_PERSONAL_DATA = "BUYER_PERSONAL_DATA";
const NOTIFY_BUYER_LIST = "NOTIFY_BUYER_LIST";
const BUYER_NOTIFY_LIST = "BUYER_NOTIFY_LIST";
const CHANGE_PASSWORD = "CHANGE_PASSWORD";
const POST_AD = 'POST_AD';
const POST_AD_ERROR = 'POST_AD_ERROR';
const MY_ADS_LIST = 'MY_ADS_LIST';
const EDIT_AD = "EDIT_AD";
const EDIT_AD_ERROR = "EDIT_AD_ERROR";
const DELETE_AD = "DELETE_AD";
const PAUSE_AD = "PAUSE_AD";
const GET_PRODUCT_DETAIL = "GET_PRODUCT_DETAIL";
const RECENTLY_VIEWED ="RECENTLY_VIEWED";
const ADD_TO_CART ="ADD_TO_CART";
const REMOVE_PRODUCT ="REMOVE_PRODUCT";
const ITEM_COUNT ="ITEM_COUNT";

export {
  CATEGORY_LIST,
  SUB_CATEGORY_LIST,
  CATEGORY_ERROR,
  BUSINESS_TYPE_LIST,
  SELLER_DATA,
  SET_ERROR,
  SET_MESSAGE,
  SET_SUCCESS,
  BUYER_PERSONAL_DATA,
  NOTIFY_BUYER_LIST,
  BUYER_NOTIFY_LIST,
  CHANGE_PASSWORD,
  POST_AD,
  POST_AD_ERROR,
  MY_ADS_LIST,
  EDIT_AD,
  EDIT_AD_ERROR,
  DELETE_AD,
  PAUSE_AD,
  GET_PRODUCT_DETAIL,
  RECENTLY_VIEWED,
  ADD_TO_CART,
  REMOVE_PRODUCT,
  ITEM_COUNT
}