const HOME_PRODUCTS = "HOME_PRODUCTS";
const FILTER_PRODUCTS = "FILTER_PRODUCTS";
const SET_ERROR = "SET_ERROR";
const HOME_RECOMMENDATION = 'HOME_RECOMMENDATION';
export {
  HOME_PRODUCTS,
  FILTER_PRODUCTS,
  SET_ERROR,
  HOME_RECOMMENDATION
};
