const SET_ERROR = "SET_ERROR";
const GET_RATING = "GET_RATING";
const GET_NEW_ITEM = "GET_NEW_ITEM";
const RECENTLY_VIEWED = "RECENTLY_VIEWED";

export {
  SET_ERROR,
  GET_RATING,
  GET_NEW_ITEM,
  RECENTLY_VIEWED
};
